---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver_config:
      gui: true

suites:
  - name: default
    run_list:
      - recipe[InfluxDB::default]
    attributes:
